### ISSUE TITLE
第十四條的項目格式跑掉了

### ISSUE THREAD

**Issue by danny50610** [HackerSir/Articles-of-association#13]
如題，不清楚原因
可能要找時機與方法修復

建議先不要直接修改

![image](https://user-images.githubusercontent.com/3949245/40412168-23affc10-5ea5-11e8-9f0f-3cfcb581ed9b.png)

**Comment by jyhsu2000** [comment]
覺得可能是GitHub渲染MD的問題
[用其他方式](https://hackersir.org/hackersir-web-2018/#/about/rule)去渲染就沒這問題
另外我也找到幾個一樣狀況的
第十九條、第二十條、第三十三條
![screenshot_20180524_000521](https://user-images.githubusercontent.com/6276648/40436862-7cc45e2c-5ee6-11e8-9d5b-fd10a7d026ed.png)
![screenshot_20180524_000543](https://user-images.githubusercontent.com/6276648/40436864-7cf1be30-5ee6-11e8-895b-99f218b0c466.png)

**Comment by jyhsu2000** [comment]
找到原因了
發生問題的地方，混了一些不一般的空白
![screenshot_20180524_202542](https://user-images.githubusercontent.com/6276648/40485372-ec815f94-5f90-11e8-9ff0-99e7746828bd.png)
解決方案：
將那些誤放的 [NO-BREAK SPACE<00a0>](http://unicode.org/cldr/utility/character.jsp?a=00A0) 改為一般以空白鍵輸入的 [SPACE<0020>](https://unicode.org/cldr/utility/character.jsp?a=0020) 應該就可以解決了

**Comment by danny50610** [comment]
00a0 ...!?
CRLF ( \r\n ) ( 0x0D 0x0A )

**Comment by jyhsu2000** [comment]
應該跟CRLF無關
畢竟代碼就不同...
[CR<000d>](https://unicode.org/cldr/utility/character.jsp?a=000D)
[LF<000a>](https://unicode.org/cldr/utility/character.jsp?a=000A)
